# Generated by Django 3.1.7 on 2021-03-12 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_planets_questions_recruitanswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.planets')),
            ],
        ),
    ]
