# Generated by Django 3.1.7 on 2021-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20210312_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='shadowHand',
            field=models.BooleanField(default=False),
        ),
    ]
