# Generated by Django 3.1.7 on 2021-03-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_recruit_shadowhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='main_sith',
            field=models.ManyToManyField(default=None, to='recruit.Sith'),
        ),
    ]
