# Generated by Django 3.1.7 on 2021-03-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_auto_20210316_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sith',
            name='shadowHandsNumber',
        ),
    ]
